# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabaniApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='project_skills', to='FabaniApp.Skill'),
        ),
    ]
