# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FabaniApp', '0002_auto_20180112_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projectInProgress',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
